from dotenv import load_dotenv
load_dotenv()

from crewai import Crew
from agents import pr_creator_agent
from tasks import pr_task

# Input parameters
repo_name = "hiteshbandhu/notes-ai-and-tech"
directory_path = "repo/"
branch_name = "master"

# Create Agents
pr_agent = pr_creator_agent()

# Create Tasks
pr_creation_task = pr_task(
    agent=pr_agent,
    repo_name=repo_name,
    directory_path=directory_path,
    branch_name=branch_name,
    title="",  # Empty string for title, will be generated by the agent
    body=""  # Empty string for body, will be generated by the agent
)

# Create Crew
crew = Crew(
    agents=[pr_agent],
    tasks=[pr_creation_task],
    verbose=2
)


# Kickoff the crew with input dictionary
result = crew.kickoff({
    "repo_name": repo_name,
    "directory_path": directory_path,
    "branch_name": branch_name,
    "title": "",  # Empty string for title, will be generated by the agent
    "body": ""  # Empty string for body, will be generated by the agent
})

# Print results
print("\n\n################################################")
print("## Here is the result")
print("################################################\n")
print(result)
