from crewai import Agent, Task, Crew
from crewai_tools import GithubSearchTool, CodeInterpreterTool, CodeDocsSearchTool

GH_REPO = "https://github.com/nginx/unit"

tool = GithubSearchTool(
    github_repo=GH_REPO,
    content_types=['code', 'issue', 'pr'] # Options: code, repo, pr, issue
)

plan_agent = Agent(
    role='Researcher',
    goal='Find and summarize the latest AI news',
    backstory="""As a researcher at a large company, your role is to analyze and 
    synthesize the latest developments in artificial intelligence. You are responsible 
    for gathering data from various sources, interpreting trends, and providing insightful 
    summaries to inform strategic decisions within the organization. Your work helps 
    stakeholders understand the current landscape of AI advancements and their potential 
    implications for business and technology.""",
    verbose=True
)

code_writing_agent = Agent(
    role='Developer',
    goal='Write code solutions based on issue given in the task',
    backstory="""As a developer specializing in automated solutions, your role 
    involves translating detailed issue plans into executable code. You leverage 
    tools like CodeInterpreter and GithubSearchTool to efficiently address and 
    resolve identified issues in GitHub repositories.""",
    verbose=True
)

tester_agent = Agent(
    role='Tester',
    goal='Validate and test code solutions',
    backstory="""As a tester, your responsibility is to rigorously test code solutions 
    generated by the code_writing_agent. You ensure that the implemented code meets 
    quality standards and adheres to the specified requirements and test strategies. 
    Your feedback guides the development process towards delivering reliable and 
    efficient solutions.""",
    verbose=True
)

task_plan_agent = Task(
    description='Find the easiest issue to solve in the repo and make a plan to solve it, referencing the files in the code to be modified or used .',
    expected_output='A list of the changes to be made to the code to solve the issue',
    agent=plan_agent,
    tools=['GithubSearchTool']
)

task_code_writing_agent = Task(
    description='Find the required',
    expected_output='Code modifications that address the identified GitHub issue',
    agent=code_writing_agent,
    tools=['CodeInterpreterTool']
)
